### ISSUE TITLE
Have generator install a fresh copy of WP in new project via WPCLI

### ISSUE THREAD

**Issue by dmoon79** [forumone/generator-web-starter-wordpress#2]
As a user, I would like the generator to load and install a fresh copy of Wordpress in a newly generated project.

**Comment by wwhurley** [comment]
This is related to forumone/generator-web-starter#1.

**Comment by wwhurley** [comment]
In 0.1.3 the generator will ask which version of WordPress to install. It will display a list of recent releases with the latest patch number, e.g. 4.4.2, 4.3.3, 4.1.7, etc. It will then download that version and copy the appropriate files into place.
