### ISSUE TITLE
Add WP-CFM as part of build

### ISSUE THREAD

**Issue by dmoon79** [forumone/generator-web-starter-wordpress#5]
Our Jenkins CI/CD procress fails when WP-CFM is not installed and enabled, so perhaps it should be included in the build?

**Comment by wwhurley** [comment]
By default WP-CFM integration is disabled. See https://github.com/forumone/web-starter/blob/1.1.x/lib/capistrano/tasks/wpcli.rake#L3. Would it be better to have the system enable WP-CFM through WP-CLI?
